CREATE TABLE OUTGO (
   ID VARCHAR(32) NOT NULL COMMENT '主键',
   MONEY DOUBLE NOT NULL COMMENT '支出金额',
   ACCOUNT_ID VARCHAR(32) NOT NULL COMMENT '支出账户',
   SHARE INT NOT NULL COMMENT '是否分享1表示是，0表示否',
   OUTGO_DATE DATE NOT NULL COMMENT '消费日期',
   INSERT_TIME DATETIME NOT NULL COMMENT '插入时间',
   TRADE_NAME VARCHAR(255) COMMENT '商家名称',
   UPDATE_TIME DATETIME COMMENT '修改时间',
   REMARK VARCHAR(500) COMMENT '备注信息'
) ENGINE = InnoDB COMMENT = '支出信息表' ROW_FORMAT = DEFAULT;

CREATE TABLE ACCOUNT (
   ID VARCHAR(32) NOT NULL COMMENT '主键',
   NAME VARCHAR(555) NOT NULL COMMENT '账户名称',
   MONEY DOUBLE NOT NULL COMMENT '金额',
   INSERT_TIME DATETIME NOT NULL COMMENT '创建时间',
   UPDATE_TIME DATETIME COMMENT '修改时间',
   REMARK VARCHAR(500) COMMENT '备注',
   USER_ID VARCHAR(32) COMMENT '所属用户',
  PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '账户信息表' ROW_FORMAT = DEFAULT CHARACTER SET utf8;

CREATE TABLE ATTACHMENT (
   ID VARCHAR(32) NOT NULL COMMENT '主键',
   ABSOLUTE_PATH VARCHAR(500) NOT NULL COMMENT '完整路径',
   INSERT_TIME DATETIME NOT NULL COMMENT '上传时间',
   RECORD_ID VARCHAR(32) NOT NULL COMMENT '对应账单主键',
  PRIMARY KEY (ID)
) ENGINE = InnoDB COMMENT = '附件表' ROW_FORMAT = DEFAULT CHARACTER SET utf8;